### ISSUE TITLE
Visiting the grave robber sometimes breaks the game

### ISSUE THREAD

**Issue by aminimalanimal** [MisuseofMana/moebiusDungeons#16]
On occasion, visiting the grave robber throws an error.

> undefined is not an object (evaluating 'this.whosSound[this.shopkeep.welcome[randomSound]].play')
> mounted — ShopControls.vue:251

Because the controls are locked until the sound file ends and the sound file is never found, they remain locked indefinitely, and the user can't continue the game.

I believe this occurs because the grave robber’s 5th welcome option (`" wantSome"`) has a leading space.

**Comment by MisuseofMana** [comment]
Thanks for the troubleshooting James! Much appreciated! Gotta love the typo errors, easy fixes!

**Comment by MisuseofMana** [comment]
This has been fixed in shopkeepData.js
